---
- hosts: taiga-dev
  remote_user: vxprt
  sudo: yes
  tasks:
  - name: install automake
    apt: name=automake state=present
  - name: install libtool
    apt: name=libtool state=present
  - name: install libffi-dev
    apt: name=libffi-dev state=present
  - name: install curl
    apt: name=curl state=present
  - name: install git
    apt: name=git state=present
  - name: install tmux
    apt: name=tmux state=present
