---
- hosts: taiga-dev
  sudo: yes
  remote_user: vxprt
  vars:
    install_dir: '/taiga-back'
    venv: 'taiga'
  tasks:
  - name: checkout taiga backend
    git: repo=https://github.com/taigaio/taiga-back.git
         dest={{install_dir}}
         version=stable

  - name: set up virtualenv settings directory
    file: path='~/.virtualenvs' state='directory'

  - name: ensure virtualenv uses utf-8 encoding by default
    copy: src='files/postmkvirtualenv' dest='~/.virtualenvs/postmkvirtualenv'

  - name: create virtualenv for taiga
    shell: virtualenv -p /usr/bin/python3.4 taiga chdir='/taiga-back' creates='{{install_dir}}/{{venv}}/bin/activate'

  - name: pip install taiga requirements
    pip: requirements={{install_dir}}/requirements.txt virtualenv={{install_dir}}/{{venv}}

  - name: add virtualenv activation to ~/.bashrc
    lineinfile: dest='~/.bashrc' create='yes' line='source {{install_dir}}/{{venv}}/bin/activate' regexp='^source \/.*\/activate.*' state='present' 
    sudo: no

  - name: add pyenv wrapper for running things through virtualenv
    template: src=templates/venv_pyenv.j2 dest={{install_dir}}/{{venv}}/bin/pyenv mode='755'