---
- hosts: taiga-dev
  remote_user: vxprt
  sudo: yes
  tasks:
  - name: install libfreetype6-dev
    apt: name=libfreetype6-dev state=present
  - name: install zlib1g-dev
    apt: name=zlib1g-dev state=present
  - name: install libzmq3-dev 
    apt: name=libzmq3-dev state=present
  - name: install libgdbm-dev
    apt: name=libgdbm-dev state=present
  - name: install libncurses5-dev
    apt: name=libncurses5-dev state=present
